version: '{build}'

environment:
  IMPOSTOR_VERSION: '1.2.2'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: false

dotnet_csproj:
  patch: false

image: Visual Studio 2019 Preview

install:
  - git submodule update --init --recursive
  - ps: dotnet tool restore

build_script:
  - ps: dotnet cake build.cake --bootstrap
  - ps: dotnet cake build.cake --pack

test: off

artifacts:
  - path: ./build/*.zip
  - path: ./build/*.tar.gz
  - path: ./build/*.dll

only_commits:
  files:
    - appveyor.yml
    - build.cake
    - Gamemodes/**/*
    - .gitmodules